export const CONFIG_JEU = {

  // Objets
  DEPTH_SOL_OBJETS: 1.5,

  // Joueur
  VITESSE_JOUEUR: 5,
  COULEUR_JOUEUR: 0xffffff,
  VIE_MAX_JOUEUR: 100,
  CLE_SPRITE_JOUEUR: "gwendo",

  // Personnages
  MIRA_FRAME_HAUTEUR: 196,
  MIRA_FRAME_LARGEUR: 108,
  MIRA_HITBOX_LARGEUR: 20,
  MIRA_HITBOX_HAUTEUR: 12,

  MIRA_FRAMES: {
    BAS:    0,
    GAUCHE: 1,
    HAUT:   2,
    DROITE: 3,
  },

  // Inventaire
  NOMBRE_SLOTS: 8,
  TOUCHE_INVENTAIRE: "I",

  // DOM
  ID_JEU: "game",
  ID_HUD: "hud",
  ID_INVENTAIRE: "inventaire",
  CLASSE_ACTIF: "actif",
  COULEUR_FOND: "#252529",

  // Son
  VOLUME_THEME: 0.2,
  VOLUME_PAS:   0.3,

  // Mode Tactile
  TACTILE_SEUIL: 15, 

  // Animations
  VEGETATION_DISTANCE_DECLENCHEMENT: 40,
  VEGETATION_DUREE_ALLER_MS:         200,
  VEGETATION_DELAI_RETOUR_MS:        50,
  VEGETATION_DUREE_RETOUR_MS:        600,
  VEGETATION_ROTATION_MAX:           0.25,
};